#!/usr/bin/env python3
"""Offline ground truth for the spectral starmap LUT (DESIGN_2026-07-24_spectral_starmap.md).

Bakes the same Planck band integrals the GPU LUT will hold, so increment 1's
[SPEC-LUT] NSLog can be checked against a number rather than against a vibe.
Run:  python3 tools/spectral_bands.py > docs/spectral_bands_reference.txt
"""
import math

h, c, k = 6.62607015e-34, 2.99792458e8, 1.380649e-23

def Bnu(nu, T):
    x = h * nu / (k * T)
    if x > 700.0:
        return 0.0
    return 2.0 * h * nu**3 / c**2 / math.expm1(x)

def bandflux(l1_um, l2_um, T, n=800):
    """Integrate Planck over [l1,l2] micron, in frequency space."""
    n1, n2 = c / (l2_um * 1e-6), c / (l1_um * 1e-6)
    s = 0.0
    for i in range(n + 1):
        nu = n1 + (n2 - n1) * i / n
        w = 0.5 if i in (0, n) else 1.0
        s += w * Bnu(nu, T)
    return s * (n2 - n1) / n

BAND_SETS = {
    "visible (DEFAULT)":  [(0.435, 0.500), (0.500, 0.590), (0.590, 0.700)],
    "hubble-like":        [(0.400, 0.550), (0.550, 0.700), (0.700, 0.950)],
    "nircam":             [(0.80, 1.65),   (1.75, 3.10),   (3.10, 5.00)],
}
TEMPS = [2400, 3200, 4500, 5772, 10000, 20000, 40000]
LINES = {"H-alpha": 0.6563, "[OIII]": 0.5007, "H-beta": 0.4861}

print("SPECTRAL STARMAP — LUT GROUND TRUTH")
print("Generated by tools/spectral_bands.py; see DESIGN_2026-07-24_spectral_starmap.md")
print()
print("Normalised band flux (each row divided by its own max channel).")
print("The GPU [SPEC-LUT] log must reproduce these to ~1e-3.")

for name, bands in BAND_SETS.items():
    print("\n=== %s ===" % name)
    print("  %7s | %-24s | %s" % ("T(K)", "R      G      B", "B/R ratio"))
    for T in TEMPS:
        f = [bandflux(lo, hi, T) for (lo, hi) in bands]
        m = max(f)
        n = [v / m for v in f]
        print("  %7d | %.3f  %.3f  %.3f       | %9.2f" % (T, n[2], n[1], n[0], f[0] / f[2]))

print("\n\n=== g-AXIS CHECK (visible G band, T=6000K) ===")
print("Confirms g^3*B(nu/g,T) == B(nu,g*T): evaluating at g*T over the FIXED")
print("observer band already carries the full g^4 amplitude. No extra multiplier.")
print("  %6s | %-14s | %-14s | %s" % ("g", "B(g*T)|obsband", "g^4 x emit", "ratio"))
T = 6000.0
lo, hi = 0.500, 0.590
for g in (0.6, 0.8, 1.0, 1.25, 1.6):
    a = bandflux(lo, hi, g * T)
    b = g**4 * bandflux(lo * g, hi * g, T)
    print("  %6.2f | %.6e | %.6e | %.4f" % (g, a, b, a / b))

print("\n\n=== EMISSION LINES: which band each falls in, vs g ===")
print("A line crossing a band edge as g changes is real deep-field behaviour.")
for setname, bands in BAND_SETS.items():
    if setname != "visible (DEFAULT)":
        continue
    print("  band set: %s  B%s G%s R%s" % (setname, bands[0], bands[1], bands[2]))
    for lname, lrest in LINES.items():
        row = []
        for g in (0.6, 0.8, 1.0, 1.25, 1.6):
            lobs = lrest / g
            which = "none"
            for bi, (blo, bhi) in enumerate(bands):
                if blo <= lobs < bhi:
                    which = "BGR"[bi]
            row.append("g=%.2f->%.3fum(%s)" % (g, lobs, which))
        print("    %-8s rest %.4fum : %s" % (lname, lrest, "  ".join(row)))
