#!/usr/bin/env python3
"""Generate SPACE SYNTH take v1 files for SS_REPLAY (frame-locked by construction: frame = ceil(t*30)).
Usage: gen_take.py orbit <out.take>            -- take 3 reproduced with orbitUpFix, ORTHO, 5400 f
       gen_take.py beat  <out.take> <onset.npy>  -- the song shot, 6840 f (see PLAN in the file)
Receiver map (main.cpp): CC20/52 zoom14 -> rho 50..5800 ; CC28/29 thetaSpin14 -> [0,thetaRange) ;
CC33 thetaRange (0 = 2pi orbit, nonzero = pi/2) ; CC30 camPhi (0 tumble, nonzero = phi=pi/2 ORBIT + orbitUpFix) ;
CC26 iscoOrbit ; CC31 phaseAmount ; CC22 exposure 7-bit log[0.01,100] (raw 64 = 1.0) ; CC54 exposure LSB (14-bit, if built).
"""
import sys, math
import numpy as np
FPS=30
def smooth(u): u=min(1.0,max(0.0,u)); return u*u*(3-2*u)
def rho_to_z14(rho): return int(round((rho-50.0)/5750.0*16383))
class Take:
    def __init__(self): self.ev=[]
    def cc(self,f,cc,v): self.ev.append((f,2,cc,int(v)))
    def cc14(self,f,msb,lsb,v14):
        v14=max(0,min(16383,int(round(v14)))); self.cc(f,msb,v14>>7); self.cc(f,lsb,v14&127)
    def on(self,f,n,vel=90): self.ev.append((f,0,n,vel))
    def off(self,f,n): self.ev.append((f,1,n,0))
    def write(self,path,frames,note):
        self.ev.sort(key=lambda e:(e[0],e[1]!=1))  # offs before ons within a frame
        with open(path,'w') as o:
            o.write("# SPACE SYNTH take v1\n# GENERATED by logs/gen_take.py -- "+note+"\n")
            o.write("# marker CC 119 ; t0 MARKER ; times SECONDS relative to t0 (frame/30, applied at ceil(t*30))\n")
            o.write("# stamps GENERATED ; unstamped 0 ; dropped 0 ; events %d ; frames %d\n"%(len(self.ev),frames))
            o.write("# E t kind(0=on,1=off,2=cc) ch a b stamped\n")
            for f,k,a,b in self.ev:
                t=f/FPS-1e-6 if f>0 else 0.0   # ceil(t*30) == f
                o.write("E %.6f %d 0 %d %d 1\n"%(t,k,a,b))
        kinds=[e[1] for e in self.ev]
        print("wrote %s: %d events (%d on, %d off, %d cc), last frame %d"%(path,len(self.ev),kinds.count(0),kinds.count(1),kinds.count(2),max(e[0] for e in self.ev)))
def holds(T,f,camPhi,thetaRange):
    T.cc(f,30,camPhi); T.cc(f,33,thetaRange); T.cc(f,26,0); T.cc(f,31,0)

def orbit(out,start=0):
    # TAKE 3 reproduced: ORTHO, SS_CAM_RHO=50, zoom p^2 rho 50->2000 (CAPPED at the old kMaxRho), theta 0->360 linear, no notes.
    N=5400; T=Take()
    for f in (0,15,30): holds(T,f,32,0)            # camPhi 32 = ORBIT + orbitUpFix ; thetaRange 0 = 2pi
    T.cc14(0,20,52,0); T.cc14(0,28,29,0)
    zcap=16383   # his ruling 2026-09-05 13:5x 'wider one': orbit ends at kMaxRho 5800
    lastz=lastt=-1
    for f in range(N):
        frac=f/(N-1); z=round(zcap*frac*frac); th=round(16383*((0.25+frac)%1.0))   # start at theta=pi/2 (the default pose)
        if z!=lastz: T.cc14(f,20,52,z); lastz=z
        if th!=lastt: T.cc14(f,28,29,th); lastt=th
        if f%150==0 and f>30: holds(T,f,32,0)
    if start>0:
        state={}; kept=[]
        for f,k,a,b in sorted(T.ev,key=lambda e:e[0]):
            if f<start: state[a]=b
            else: kept.append((f-start,k,a,b))
        T.ev=[(0,2,a,b) for a,b in state.items()]+kept; N=N-start
    T.write(out,N,"ORBIT take 3 with orbitUpFix: ortho, rho 50->5800 p^2 (his wider ruling), theta 360 from pi/2, no notes"+(f"; EXCERPT from frame {start}" if start else ""))

# ---------------- THE SONG SHOT (PLAN v1, for his ruling) ----------------
# 120 BPM, 15 frames/beat, 60 frames/bar. Sections from the per-bar energy map (bar = 2 s):
SECTIONS=[  # (start_bar, end_bar_exclusive, name, rho_target, pump_depth, note)
 ( 0, 15,"intro",      1800, 0.10, [51]),            # Eb2 -- root only
 (15, 16,"breath",     1800, 0.00, None),
 (16, 30,"B build",    1200, 0.15, [51,58]),         # Eb2 + Bb2 (fifth)
 (30, 32,"break2",     1400, 0.05, None),
 (32, 56,"C full",      700, 0.22, [51,58,63]),      # + Eb3 (octave), no third: the track has none
 (56, 64,"riff",        900, 0.15, [58,63]),
 (64, 72,"breakdown",  1600, 0.00, None),
 (72, 96,"DROP",        400, 0.30, [51,58,63,70]),   # + Bb3
 (96,108,"last",        600, 0.22, [51,58,63]),
 (108,112,"outro",     1500, 0.05, None),
 (112,114,"tail",      2000, 0.00, None),
]
def beat(out,onset_path,exp14=False,start=0):
    N=6840; T=Take(); of=np.load(onset_path); ofps=22050/256
    # kick onsets -> frames, snapped to the eighth-note grid (7.5 f) when within 2 frames, else dropped
    thr=of.mean()+2*of.std()
    pk=[i for i in range(1,len(of)-1) if of[i]>thr and of[i]>=of[i-1] and of[i]>=of[i+1]]
    m=[]
    for i in pk:
        if not m or (i-m[-1])/ofps>0.1: m.append(i)
    kf=np.array(m)/ofps*FPS
    # grid phase: find offset (frames) that maximises onsets near beat multiples
    best=max(((sum(1 for k in kf if abs(((k-ph)%15+7.5)%15-7.5)<=1.5),ph) for ph in np.arange(0,15,0.5)))
    ph=best[1]; kicks=[]
    for k in kf:
        g=round((k-ph)/7.5)*7.5+ph
        if abs(k-g)<=2.0: kicks.append(int(round(g)))
    kicks=sorted(set(kicks)); print("grid phase %.1f f, %d/%d onsets on the eighth grid"%(ph,len(kicks),len(kf)))
    # camera: ORTHO orbit, phi=90 + upfix, theta 0->360 over the track, rho eased between section targets (8-bar ease)
    for f in (0,15,30): holds(T,f,32,0)
    T.cc14(0,20,52,rho_to_z14(SECTIONS[0][3])); T.cc14(0,28,29,0)
    # per-frame rho: piecewise smoothstep from previous target to next over the first 8 bars (480 f) of each section
    rho=np.zeros(N); prev=SECTIONS[0][3]
    for (b0,b1,name,rt,depth,notes) in SECTIONS:
        f0,f1=b0*60,min(N,b1*60); L=min(480,f1-f0)
        for f in range(f0,f1):
            u=(f-f0)/L if L>0 else 1.0; rho[f]=prev+(rt-prev)*smooth(u)
        prev=rt
    # exposure: baseline 1.0 (raw 64.0 / 8192 in 14-bit); per kick a dip of `depth` (section), attack 1 f, exp release tau 6 f
    depth=np.zeros(N)
    for (b0,b1,name,rt,d,notes) in SECTIONS: depth[b0*60:min(N,b1*60)]=d
    env=np.zeros(N)
    for k in kicks:
        if k<N:
            for j in range(k,min(N,k+20)): env[j]=max(env[j],math.exp(-(j-k)/6.0))
    expo=1.0-depth*env                     # multiplier, >= 0.7
    lo,hi=math.log(0.01),math.log(100.0)
    t01=(np.log(np.maximum(expo,0.01))-lo)/(hi-lo)
    lastz=lastt=laste=-1
    for f in range(N):
        z=rho_to_z14(rho[f]); th=round(16383*((0.25+f/(N-1))%1.0))   # start at theta=pi/2
        if z!=lastz: T.cc14(f,20,52,z); lastz=z
        if th!=lastt: T.cc14(f,28,29,th); lastt=th
        if exp14:
            e=int(round(t01[f]*16383))
            if e!=laste: T.cc14(f,22,54,e); laste=e
        else:
            e=int(round(t01[f]*127))
            if e!=laste: T.cc(f,22,e); laste=e
        if f%150==0 and f>30: holds(T,f,32,0)
    # notes: ONE chord held per section (held = cheap), released at the section end (few re-evolutions)
    for (b0,b1,name,rt,d,notes) in SECTIONS:
        if not notes: continue
        f0,f1=b0*60,min(N-2,b1*60-1)
        for n in notes: T.on(f0,n); T.off(f1,n)
    if start>0:
        # EXCERPT: keep the last value of every CC before `start` as frame-0 state, shift the rest
        state={}; notes_on=set(); kept=[]
        for f,k,a,b in sorted(T.ev,key=lambda e:e[0]):
            if f<start:
                if k==2: state[a]=b
                elif k==0: notes_on.add(a)
                elif k==1: notes_on.discard(a)
            else: kept.append((f-start,k,a,b))
        T.ev=[(0,2,a,b) for a,b in state.items()]+[(0,0,n,90) for n in sorted(notes_on)]+kept
        N=N-start
    T.write(out,N,"SONG SHOT plan v1 (Eb/Bb chords): ortho orbit 360, rho per section, exposure pump on kicks, one held chord per section"+(f"; EXCERPT from frame {start}" if start else ""))
    print("kicks used:",len(kicks),"| chords:",sum(1 for s in SECTIONS if s[5]),"| min exposure %.2f"%expo.min())

if __name__=="__main__":
    if sys.argv[1]=="orbit":
        st=int(sys.argv[sys.argv.index("--start-frame")+1]) if "--start-frame" in sys.argv else 0
        orbit(sys.argv[2],start=st)
    elif sys.argv[1]=="beat":
        st=int(sys.argv[sys.argv.index("--start-frame")+1]) if "--start-frame" in sys.argv else 0
        beat(sys.argv[2],sys.argv[3],exp14=("--14bit" in sys.argv),start=st)
